# Generated by Django 5.2.4 on 2025-07-04 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('nombre', models.CharField(default='Lección', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dificultad', models.CharField(blank=True, max_length=50)),
                ('mundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='lessons.mundo')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDidactico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.categoria')),
                ('niveles', models.ManyToManyField(related_name='materiales', to='lessons.nivel')),
            ],
        ),
    ]
