# Generated by Django 5.2.1 on 2025-07-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='dificultad',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='nivel',
        ),
        migrations.AddField(
            model_name='nivel',
            name='cantidad_ejercicio',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Ejercicios'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
