# Generated by Django 5.2.1 on 2025-07-29 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('rewards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recompensa',
            name='es_avatar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.nivel'),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
