# Generated by Django 5.2.1 on 2025-07-29 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_recompensa_es_avatar_alter_recompensa_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recompensa',
            name='es_avatar',
        ),
    ]
