# Generated by Django 5.2.1 on 2025-07-30 21:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_nivel_dificultad_remove_nivel_nivel_and_more'),
        ('rewards', '0004_remove_recompensa_es_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progreso',
            name='nivel',
        ),
        migrations.AddField(
            model_name='progreso',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 7, 30, 21, 0, 26, 720986, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progreso',
            name='mundo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.mundo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progreso',
            name='niveles_completados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
