# Generated by Django 5.2.1 on 2025-07-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_perfil_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='apellidos_padre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.CharField(blank=True, default='avatar1.png', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre_padre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_menor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
